job_analytics:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'job_analytics'
      schema: 'main'
      schemas_and_paths:
        main: '../data/jobs.db'
      schema_directory: '../data'